# Generated by Django 3.1 on 2020-09-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200904_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
