# Generated by Django 3.1 on 2020-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_subs_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatters',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subs',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subs',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
